django/lab3/URLShortener/URLShortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shortener/', include('shortener.urls'))
]

django/lab3/URLShortener/shortener/urls.py
from django.urls import path
from . import views

app_name = 'shortener'
urlpatterns = [
    path('', views.index, name='index'),
    path('save/', views.save_url, name='save'),
    path('<str:code>/', views.forward, name='forward'),
]

django/lab3/URLShortener/shortener/models.py
from django.db import models

# Create your models here.
class ShortenedURL(models.Model):
    code = models.CharField(max_length=5)
    url = models.URLField()
    counter = models.IntegerField(default = 0)

    def __str__(self):
        return f"{self.code} -- {self.url}"

django/lab3/URLShortener/shortener/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import ShortenedURL
from django.urls.base import reverse
from django.http import HttpResponseRedirect

import random
import string

# Create your views here.
def index(req):
    urls = ShortenedURL.objects.all()
    context = {
        'urls': urls
    }
    return render(req, 'shortener/index.html', context)

def save_url(req):
    characters = string.ascii_letters + string.digits
    code = ""
    while len(code) < 5:
        code += random.choice(characters)
    
    url = req.POST['url']
    # form = req.POST
    # url = form['url']
    
    shortened_url = ShortenedURL(code=code, url=url)
    shortened_url.save()
    
    return HttpResponseRedirect(reverse('shortener:index'))

def forward(req, code):
    if len(code) != 5:
        return HttpResponseRedirect(reverse('shortener:index'))
    
    shortened_url = get_object_or_404(ShortenedURL, code=code)
    shortened_url.counter += 1
    shortened_url.save()
    url = shortened_url.url

    return redirect(url)
        

django/lab3/URLShortener/shortener/templates/shortener/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Shorten your sites here!</h1>
    <form action="{% url 'shortener:save' %}" method="post">
        {% csrf_token %}
        <input required type="url" placeholder="url to short" name="url">
        <input type="submit" value="Submit">
    </form>
    <table>
        <tr>
            <th>Visits</th>
            <th>Code</th>
            <th>URL</th>
        </tr>
        {% for url in urls%}
        <tr>
            <td>{{url.counter}}</td>
            <td><a href="{% url 'shortener:forward' url.code %}">{{url.code}}</a></td>
            <td><a href="{% url 'shortener:forward' url.code %}">{{url.url}}</a></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>